apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-app
  namespace: argo
  annotations:
    argocd-image-updater.argoproj.io/image-list: myalias=quay.io/rockchico2/catnip
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argo/git-creds
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  destination:
    namespace: myapp
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argoui-helm/myapp
    repoURL: https://github.com/rockchico/gitops-cookbook-sc.git
    targetRevision: main

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true