apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgd-app
  namespace: argo
spec:
  destination:
    namespace: bgd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/rockchico/gitops-cookbook-sc.git
    path: ch07/bgd
    targetRevision: main
  syncPolicy:
    # automated: {}
    
    # Para observar modificações no repositório e reaplicar em
    # caso de mudanças
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Cria o namespace de destino